name: Update WakaTime Stats

on:
  schedule:
    # 毎日午前0時に実行
    - cron: "0 0 * * *"
  workflow_dispatch: # 手動実行も可能

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          SHOW_TITLE: "false"
          SHOW_LINE_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_EDITORS: "true"
          SHOW_LOC_CHART: "true"
          SHOW_LANGUAGE_CHART: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_OVERVIEW: "true"
          SHOW_SHORT_INFO: "true"
